language: python

python:
    - '3.8'

install:
    - pip install -r requirements/dev.txt

env:
    global:
        - PYTHONPATH=/home/travis/build/gcallah/SeniorDesignTemplate

script:
    - make tests
